### ISSUE TITLE
The GPU memory about theano-mc-cnn

### ISSUE THREAD

**Issue by TrackingBird** [epiception/theano-mc-cnn#4]
Hi epiception, thanks for your contributions. I have a little question here. As we know, ,[mc-cnn](https://github.com/jzbontar/mc-cnn) need the GPU with at least 6 GB on the KITTI data set and 12 GB to run on the Middlebury data set. Does theano-mc-cnn also need the same GPU memory like mc-cnn. Can I run the code on the compute with 4 GPU memory. Thanks very much for your answer,  have a nice day.

**Comment by epiception** [comment]
Hi TrackingBird, 

I implemented this at a time when I did not have access to a GPU. But this is a simpler implementation that mines patches only from a few frames. Further, this is the fast architecture, so very few filters. I think the reason for that kind of memory requirement on their implementation is probably for the accurate architecture, and they seem to either load the patches in memory or apply the matching cost operation in GPU. 

My model should not be that GPU memory intensive.
Good day to you as well. :smile:
